org_id               = "157305482127"
billing_account      = "014A32-6EFDA8-492638"
default_region       = "us-central1"
group_org_admins     = "gcp-organization-admins@budita.dev"
group_billing_admins = "gcp-billing-admins@budita.dev"
github_repo_name     = "gcp-foundation"
github_user_name     = "rajesh-nitc"