org_id                           = "157305482127"
terraform_service_account        = "org-terraform@prj-b-seed-6949.iam.gserviceaccount.com"
billing_account                  = "014A32-6EFDA8-492638"
group_email                      = "gcp_gke_admin@budita.dev"
app_infra_pipeline_cloudbuild_sa = "869249260424@cloudbuild.gserviceaccount.com"
app_cicd_project_id              = "prj-gke-c-cicd-pipeline-7989"
cicd_sa                          = "cicd-sa@prj-gke-c-cicd-pipeline-7989.iam.gserviceaccount.com"
bkt_tfstate                      = "gke-tfstate-7864"