project_id              = "prj-onprem-o-connectivity-53cd"
project_service_account = "project-service-account@prj-onprem-o-connectivity-53cd.iam.gserviceaccount.com"
default_region1         = "us-central1"
private_ip              = "10.2.0.5"
hostname                = "host1"